### PR TITLE
Add #odd and #even to all methods lists

### PR DESCRIPTION
**Pull request by edg2s**
These are new in jQuery 3.5

### CODE REVIEW

**Comment by jdforrester** [comment]
How do we want to handle this? Mark them as "deprecated" as "This function did not exist until jQuery 3.5"?

**Comment by edg2s** [comment]
Handle what? What's deprecated?

**Comment by jdforrester** [comment]
Using .odd() on jquery 3.1 will not work; shouldn't we warn about this kind of breakage?

**Comment by edg2s** [comment]
Well that wouldn't be part of our deprecations, that would be a much bigger project to track when every feature was introduced. We'd have to know that $.find was introduced in 0.2 or whatever. I'm not sure it would be worth it.

**Pull request merged**
