### PR TITLE
Disallow querying the DOM for state using class methods

### PR DESCRIPTION
**Pull request by edg2s**
This is a more specific version of 'no-class' that specifically
disallows reading document state from the DOM, which would
be bad pracitce in a model-view application.

### CODE REVIEW

**Comment by brion** [comment]
Can you explain why this is included? I don't understand the purpose of the rule, and find the message very confusing.

**Comment by jdforrester** [comment]
> Can you explain why this is included? I don't understand the purpose of the rule, and find the message very confusing.

Querying the DOM state is exceptionally expensive compared to holding it in your app state; writing app state out to DOM and reading it back is an anti-pattern. Obviously where it's used to do server->client initial communication it's fine, and should be inline-escaped. Happy to tweak wording if that helps?

**Comment by brion** [comment]
Ah, so it's specific to model-view applications where the DOM does not hold authoritative information?

Maybe put something about that in the warning message... Right now it's "Don't query the DOM for state information" which makes literally no sense out of context to me. What else would I query? :)

**Comment by brion** [comment]
Maybe something like "Consider maintaining app state in memory instead of using slow DOM access" but that's not always actionable, since you just have to paper over it with a suppression comment if that's not what's going on and you're initializing something from server-provided HTML state.

**Comment by jdforrester** [comment]
I suppose that since we started down the performance engineering avenue, everything looks like a nail. Fair. :-)

**Pull request merged**
