### PR TITLE
Replace Array#indexOf with Array#includes

### PR DESCRIPTION
**Pull request by edg2s**

### CODE REVIEW

**Comment by jdforrester** [comment]
Does this effectively change our eslint compatibility? With this, we're now increasing our required node level above what eslint 2 requires, I think?

**Comment by edg2s** [comment]
Hopefully not as we were already using Array.includes...

**Comment by edg2s** [comment]
Also we only claim to support ESLint 2.3, not the lowest version of Node that that supports. You can use 2.3 with Node 14...

**Comment by edg2s** [comment]
Array.includes requires Node 6, but so does Object.assign, and probably a bunch of our dependencies.

**Comment by jdforrester** [comment]
WFM. Maybe we can put the engine requirement in package.json for clarity?

**Pull request merged**
